services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "voucher-db"
    container_name: voucher-postgres-db
    environment:
      POSTGRES_DB: vouchers
      POSTGRES_USER: voucher_admin
      POSTGRES_PASSWORD: voucher88
      PGDATA: /data/voucher-db
    volumes:
      - dbvouch:/data/voucher-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - voucher-network

  voucher-app:
     image: "voucher-application:local"
     container_name: voucher-system
     depends_on:
       - postgres
     ports:
       - "8080:8080"
     restart: unless-stopped
     networks:
       - voucher-network
volumes:
  dbvouch:
    external: true

networks:
  voucher-network:
    driver: bridge
