services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "voucher-db"
    container_name: voucher-postgres-db
    environment:
      POSTGRES_DB: vouchers
      POSTGRES_USER: voucher_admin
      POSTGRES_PASSWORD: voucher88
      PGDATA: /data/voucher-db
    volumes:
      - dbvouch:/data/voucher-db
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  dbvouch:
    external: true